Update llfuse-1.3.6 to 1.3.8 to fix borg mount, add llfuse Slackbuild and notes

diff --git a/source/SlackBuild/llfuse/llfuse.SlackBuild b/source/SlackBuild/llfuse/llfuse.SlackBuild
--- a/source/SlackBuild/llfuse/llfuse.SlackBuild
+++ b/source/SlackBuild/llfuse/llfuse.SlackBuild
@@ -1,32 +1,39 @@
 #!/bin/sh
 
-# Slackware build script for LLFUSE
+# Slackware build script for "llfuse".
+# Adapted by kubedzero from https://slackbuilds.org/repository/14.2/python/llfuse/
 
-# Copyright 2015 Andrzej Telszewski, Sabadell
+# Copyright 2015-2016 Andrzej Telszewski, Sabadell
+# Copyright 2016 Marcel Saegebarth <marc@mos6581.de>
 # All rights reserved.
 #
-# Redistribution and use of this script, with or without modification, is
-# permitted provided that the following conditions are met:
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are
+# met:
 #
-# 1. Redistributions of this script must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
+# * Redistributions of source code must retain the above copyright
+# notice, this list of conditions and the following disclaimer.
 #
-#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
-#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
-#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
-#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
-#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
-#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
-#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
-#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
+# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
+# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
+# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
+# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
+# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
+# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
+# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# Set these to tell the script what input/output files to use
 PRGNAM=llfuse
 VERSION=${VERSION:-1.3.8}
+ARCHIVE="python-$PRGNAM-release-$VERSION"
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
+# Determine architecture of build system
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
     i?86) ARCH=i486 ;;
@@ -34,11 +41,6 @@ if [ -z "$ARCH" ]; then
        *) ARCH=$( uname -m ) ;;
   esac
 fi
-
-CWD=$(pwd)
-TMP=${TMP:-/tmp/SBo}
-PKG=$TMP/package-$PRGNAM
-OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
@@ -54,14 +56,27 @@ else
   LIBDIRSUFFIX=""
 fi
 
-set -e
+# Halt on errors and print out each variable's state
+set -ex
 
+# NOTE: script checks working directory, execute from within same dir
+CWD=$(pwd)
+TMP=${TMP:-/tmp/SBo}
+PKG=$TMP/package-$PRGNAM
+OUTPUT=${OUTPUT:-/tmp}
+
+# remove existing build output and recreate build directories
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
-cd $PRGNAM-$VERSION
+rm -rf "$PRGNAM-$VERSION" "$ARCHIVE"
+
+# Unzip the repository code, rename it, and move into that directory
+unzip "$CWD/$ARCHIVE.zip"
+mv "$ARCHIVE" "$PRGNAM-$VERSION"
+cd "$PRGNAM-$VERSION"
+
+# Set permissions on files in the unzipped repository
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
@@ -69,25 +84,39 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
+# Assumes Cython is already installed, build the C files in the repo
+python setup.py build_cython
+
+# Run the install using GCC, outputting to the $PKG build output
 python setup.py install --root=$PKG
 
-# Python 3 support.
+# Python 3 support, rebuild using Python3
 if $(python3 -c 'import sys' 2>/dev/null); then
+  python3 setup.py build_cython
   python3 setup.py install --root=$PKG
 fi
 
+# Consecutive filtering of files and text to confirm the output is present
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
+# Copy the documentation files into the $PKG build output
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/html
-cp -a examples LICENSE $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a doc/html/*.html doc/html/searchindex.js doc/html/_static \
-      $PKG/usr/doc/$PRGNAM-$VERSION/html
+cp -a examples Changes.rst LICENSE README.rst $PKG/usr/doc/$PRGNAM-$VERSION
+
+## Copy the HTML documentation as well. Needs a certain Python build target,
+## otherwise this doesn't succeed. Commented out for compatibility
+# mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/html
+# cp -a doc/html/*.html doc/html/searchindex.js doc/html/_static \
+#       $PKG/usr/doc/$PRGNAM-$VERSION/html
+
+# Copy the build script to the $PKG build output as well
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
+# Copy the Slackware slack-desc text file to the $PKG build output
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
+# Go to the $PKG build output and actually build the compiled TXZ package
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
